# start docker compose:
# sudo docker compose up -d

services:
  jiascheduler-mysql:
    image: mysql:latest
    restart: always
    container_name: jiascheduler-mysql
    networks:
      - jiascheduler-network
    volumes:
      - jiascheduler_mysql_data:/var/lib/mysql
      - jiascheduler_mysql_logs:/var/log/mysql
    environment:
      - TZ=Asia/Shanghai # 设置时区
      - MYSQL_ROOT_PASSWORD=kytHmeBR4Vg
      - MYSQL_DATABASE=jiascheduler # 自动创建数据库
    ports:
      - 3306:3306

  jiascheduler-redis:
    image: redis:latest
    restart: always
    container_name: jiascheduler-redis
    networks:
      - jiascheduler-network
    volumes:
      - jiascheduler_redis_data:/data
      - jiascheduler_redis_logs:/logs
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=3DGiuazc7wkAppV3
    command: ["redis-server", "--requirepass", "3DGiuazc7wkAppV3"]

  jiascheduler-console:
    restart: always
    image: iwannay/jiascheduler
    depends_on:
      - jiascheduler-mysql
      - jiascheduler-redis
    container_name: jiascheduler-console
    networks:
      - jiascheduler-network
    ports:
      - "9090:9090"
    volumes:
      - ./console.toml:/root/.jiascheduler/console.toml
    command: ["./jiascheduler", "--console-bind-addr", "0.0.0.0:9090"]

volumes:
  jiascheduler_mysql_data:
    name: jiascheduler_mysql_data
  jiascheduler_mysql_logs:
    name: jiascheduler_mysql_logs
  jiascheduler_redis_data:
    name: jiascheduler_redis_data
  jiascheduler_redis_logs:
    name: jiascheduler_redis_logs

networks:
  jiascheduler-network:
    driver: bridge
