//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, Default)]
#[sea_orm(table_name = "job_organizer_release_node")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub version: String,
    pub node_id: String,
    pub name: String,
    pub node_type: String,
    pub flow_type: String,
    pub task_type: String,
    pub dispatch_data: Option<Json>,
    pub props: Option<Json>,
    #[sea_orm(column_type = "Text")]
    pub condition: String,
    pub bind_ip: Option<Json>,
    pub created_time: DateTimeLocal,
    pub updated_time: DateTimeLocal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
