//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, Default)]
#[sea_orm(table_name = "job_exec_history")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub instance_id: String,
    pub schedule_id: String,
    pub eid: String,
    pub job_type: String,
    pub bundle_script_result: Option<Json>,
    pub exit_status: String,
    pub exit_code: i32,
    #[sea_orm(column_type = "Text")]
    pub output: String,
    pub start_time: Option<DateTimeLocal>,
    pub end_time: Option<DateTimeLocal>,
    pub created_time: DateTimeLocal,
    pub updated_time: DateTimeLocal,
    pub created_user: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
