//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, Default)]
#[sea_orm(table_name = "job_running_status")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub bind_ip: String,
    pub bind_namespace: String,
    pub schedule_type: String,
    pub job_type: String,
    pub eid: String,
    pub schedule_id: String,
    pub schedule_status: String,
    pub run_status: String,
    pub exit_status: String,
    pub exit_code: i32,
    pub dispatch_result: Option<Json>,
    pub start_time: Option<DateTimeUtc>,
    pub end_time: Option<DateTimeUtc>,
    pub next_time: Option<DateTimeUtc>,
    pub prev_time: Option<DateTimeUtc>,
    pub updated_user: String,
    pub updated_time: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
