//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, Default)]
#[sea_orm(table_name = "workflow_process")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub process_id: String,
    pub process_name: String,
    pub workflow_id: u64,
    pub version_id: u64,
    pub timer_id: u64,
    pub process_args: Option<Json>,
    pub process_status: String,
    pub current_run_id: String,
    pub current_node_id: String,
    pub current_node_status: String,
    pub created_user: String,
    pub created_time: DateTimeLocal,
    pub updated_time: DateTimeLocal,
    #[serde(default)]
    pub is_deleted: bool,
    pub deleted_at: Option<DateTimeLocal>,
    #[serde(default)]
    pub deleted_by: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
