//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, Default)]
#[sea_orm(table_name = "workflow_process_edge")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub process_id: u64,
    pub run_id: String,
    pub edge_id: String,
    pub edge_type: String,
    pub edge_val: String,
    pub props: Option<Json>,
    pub source_node_id: String,
    pub target_node_id: String,
    pub created_user: String,
    pub created_time: DateTimeLocal,
    pub updated_time: DateTimeLocal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
