ALTER TABLE job
ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL,
ADD COLUMN deleted_by varchar(50) NOT NULL DEFAULT '' COMMENT '删除人';

ALTER TABLE job_timer
ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL,
ADD COLUMN deleted_by varchar(50) NOT NULL DEFAULT '' COMMENT '删除人';

ALTER TABLE job_supervisor
ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL,
ADD COLUMN deleted_by varchar(50) NOT NULL DEFAULT '' COMMENT '删除人';

ALTER TABLE job_bundle_script
ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL,
ADD COLUMN deleted_by varchar(50) NOT NULL DEFAULT '' COMMENT '删除人';

ALTER TABLE job_schedule_history
ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL,
ADD COLUMN deleted_by varchar(50) NOT NULL DEFAULT '' COMMENT '删除人';
